### ISSUE TITLE
nem működik 

### ISSUE THREAD

**Issue by dominuscado** [vargalex/plugin.video.animeaddicts#1]
nem tudnád működésre bírni új Kodin? gondolom a Python 2.x-szel van probléma

**Comment by dtechsrv** [comment]
Milyen OS-en és hányas verziójú Kodi-val próbálod?
Csak mert a Leia (v18) után már Python 3 van, azzal a jelenlegi kód nem kompatibilis.

**Comment by dominuscado** [comment]
csak androidon Kodizok, 20.2-es verziójú a Kodi . Nixtoons-on animézek, de jó lenne magyar is.

**Comment by vargalex** [comment]
Amint időm lesz, ránézek, de nem ígérek semmit... Ha lesz, akkor a topicba is beírom. Egyébként az van, amit a kolléga írt, a jelenlegi verzió csak Leia-ig megy, mert Python 2 kell neki.

**Comment by vargalex** [comment]
Elkezdem én is, de @dtechsrv kolléga gyorsabb volt, így merge-eltem az ő pull request-jét.
